meta_product_name: "Findo"
meta_title: "Findo - Votre solution pour trouver LE cadeau !"
meta_description: "Pour qui ? Quoi ? Quel budget ? Quelle occasion ? Findo vous aide avec votre recherche du cadeau parfait pour vos proches ! "
meta_image: "cover.png" # should exist in `app/assets/images/`
